export const PLATFORMS = [
  { id:'github',     name:'GitHub',     color:'#6e40c9', icon:'⌨️', bx:-12,  bz:-3,  row:'near' },
  { id:'instagram',  name:'Instagram',  color:'#e1306c', icon:'📸', bx:-7,   bz:-3,  row:'near' },
  { id:'twitter',    name:'Twitter/X',  color:'#1da1f2', icon:'𝕏',  bx:-3,   bz:-2,  row:'near' },
  { id:'youtube',    name:'YouTube',    color:'#ff0000', icon:'▶️', bx:2,    bz:-2,  row:'near' },
  { id:'reddit',     name:'Reddit',     color:'#ff4500', icon:'🔴', bx:6,    bz:-3,  row:'near' },
  { id:'snapchat',   name:'Snapchat',   color:'#fffc00', icon:'👻', bx:11,   bz:-3,  row:'near' },
  { id:'linkedin',   name:'LinkedIn',   color:'#0077b5', icon:'💼', bx:-10,  bz:-8,  row:'mid'  },
  { id:'telegram',   name:'Telegram',   color:'#229ed9', icon:'✈️', bx:-5,   bz:-9,  row:'mid'  },
  { id:'tiktok',     name:'TikTok',     color:'#010101', icon:'🎵', bx:0,    bz:-8,  row:'mid'  },
  { id:'pinterest',  name:'Pinterest',  color:'#e60023', icon:'📌', bx:5,    bz:-9,  row:'mid'  },
  { id:'steam',      name:'Steam',      icon:'🎮',       color:'#4a90d9', bx:9,   bz:-8,  row:'mid'  },
  { id:'hackernews', name:'HackerNews', color:'#ff6600', icon:'🧡', bx:-8,   bz:-14, row:'far'  },
  { id:'devto',      name:'Dev.to',     color:'#08090a', icon:'👩‍💻', bx:-3,  bz:-15, row:'far'  },
  { id:'gitlab',     name:'GitLab',     color:'#fc6d26', icon:'🦊', bx:2,    bz:-14, row:'far'  },
  { id:'tumblr',     name:'Tumblr',     color:'#35465c', icon:'📝', bx:7,    bz:-15, row:'far'  },
  { id:'medium',     name:'Medium',     color:'#00ab6c', icon:'✍️', bx:-6,   bz:-6,  row:'mid'  },
  { id:'quora',      name:'Quora',      color:'#b92b27', icon:'❓', bx:3,    bz:-6,  row:'mid'  },
  { id:'flickr',     name:'Flickr',     color:'#ff0084', icon:'📷', bx:-1,   bz:-12, row:'far'  },
  { id:'soundcloud', name:'SoundCloud', color:'#ff5500', icon:'🎧', bx:6,    bz:-12, row:'far'  },
  { id:'pastebin',   name:'Pastebin',   color:'#02aaab', icon:'📋', bx:-11,  bz:-12, row:'far'  },
  { id:'facebook',   name:'Facebook',   color:'#1877f2', icon:'F', bx:12,   bz:-7,  row:'mid'  },
  { id:'sharechat',  name:'ShareChat',  color:'#ff6b35', icon:'SC', bx:-13,  bz:-17, row:'far'  },
  { id:'koo',        name:'Koo',        color:'#f5c518', icon:'K', bx:-9,   bz:-18, row:'far'  },
  { id:'discord',    name:'Discord',    color:'#5865f2', icon:'D', bx:-4,   bz:-18, row:'far'  },
  { id:'joshmoj',    name:'Josh/Moj',   color:'#ff1493', icon:'JM', bx:1,    bz:-18, row:'far'  },
  { id:'meesho',     name:'Meesho',     color:'#9f2089', icon:'M', bx:6,    bz:-18, row:'far'  },
  { id:'olxindia',   name:'OLX India',  color:'#23e5db', icon:'OLX', bx:11,   bz:-18, row:'far'  },
  { id:'naukri',     name:'Naukri.com', color:'#457eff', icon:'N', bx:-13,  bz:-22, row:'far'  },
  { id:'jiocinema',  name:'JioCinema',  color:'#d9008d', icon:'JC', bx:-7,   bz:-22, row:'far'  },
  { id:'mxtakatak',  name:'MX TakaTak', color:'#00c2ff', icon:'MX', bx:-1,   bz:-22, row:'far'  },
  { id:'roposo',     name:'Roposo',     color:'#f97316', icon:'R', bx:5,    bz:-22, row:'far'  },
  { id:'whatsapp',   name:'WhatsApp Business', color:'#25d366', icon:'WA', bx:11, bz:-22, row:'far'  },
]

export const getPlatformByName = (name) =>
  PLATFORMS.find(p => p.name === name || p.name.toLowerCase() === name.toLowerCase())
